# Generated by Django 5.0.2 on 2024-12-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_contact_client_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='mchellechi@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='message',
            field=models.TextField(),
        ),
    ]
