# Generated by Django 5.0.2 on 2024-12-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_client_email_alter_client_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='number',
        ),
    ]
